version: '3'
services:
  angular-app:
    image: wifek230/frontwifek
    container_name: docker-compose-angular-app
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
    networks:
      - my-network
    

networks:
  my-network:
